package com.lut.model;

public class TbCustomer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer.customerName 
     *
     * @mbggenerated
     */
    private String customername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer.customerPass 
     *
     * @mbggenerated
     */
    private String customerpass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_customer.customerTel
     *
     * @mbggenerated
     */
    private String customertel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer.customerName 
     *
     * @return the value of tb_customer.customerName 
     *
     * @mbggenerated
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer.customerName 
     *
     * @param customername  the value for tb_customer.customerName 
     *
     * @mbggenerated
     */
    public void setCustomername(String customername) {
        this.customername= customername== null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer.customerPass 
     *
     * @return the value of tb_customer.customerPass 
     *
     * @mbggenerated
     */
    public String getCustomerpass() {
        return customerpass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer.customerPass 
     *
     * @param customerpass  the value for tb_customer.customerPass 
     *
     * @mbggenerated
     */
    public void setCustomerpass(String customerpass) {
        this.customerpass= customerpass == null ? null : customerpass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_customer.customerTel
     *
     * @return the value of tb_customer.customerTel
     *
     * @mbggenerated
     */
    public String getCustomertel() {
        return customertel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_customer.customerTel
     *
     * @param customertel the value for tb_customer.customerTel
     *
     * @mbggenerated
     */
    public void setCustomertel(String customertel) {
        this.customertel = customertel == null ? null : customertel.trim();
    }
}