package com.lut.model;

public class TbGoods {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goodsID
     *
     * @mbggenerated
     */
    private Integer goodsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goodsName
     *
     * @mbggenerated
     */
    private String goodsname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goodsTypeID
     *
     * @mbggenerated
     */
    private Integer goodstypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goodsDescript
     *
     * @mbggenerated
     */
    private String goodsdescript;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goodsUnitPrice
     *
     * @mbggenerated
     */
    private Integer goodsunitprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.goodsImageName
     *
     * @mbggenerated
     */
    private String goodsimagename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goods.sellCount
     *
     * @mbggenerated
     */
    private Integer sellcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goodsID
     *
     * @return the value of tb_goods.goodsID
     *
     * @mbggenerated
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goodsID
     *
     * @param goodsid the value for tb_goods.goodsID
     *
     * @mbggenerated
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goodsName
     *
     * @return the value of tb_goods.goodsName
     *
     * @mbggenerated
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goodsName
     *
     * @param goodsname the value for tb_goods.goodsName
     *
     * @mbggenerated
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname == null ? null : goodsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goodsTypeID
     *
     * @return the value of tb_goods.goodsTypeID
     *
     * @mbggenerated
     */
    public Integer getGoodstypeid() {
        return goodstypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goodsTypeID
     *
     * @param goodstypeid the value for tb_goods.goodsTypeID
     *
     * @mbggenerated
     */
    public void setGoodstypeid(Integer goodstypeid) {
        this.goodstypeid = goodstypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goodsDescript
     *
     * @return the value of tb_goods.goodsDescript
     *
     * @mbggenerated
     */
    public String getGoodsdescript() {
        return goodsdescript;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goodsDescript
     *
     * @param goodsdescript the value for tb_goods.goodsDescript
     *
     * @mbggenerated
     */
    public void setGoodsdescript(String goodsdescript) {
        this.goodsdescript = goodsdescript == null ? null : goodsdescript.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goodsUnitPrice
     *
     * @return the value of tb_goods.goodsUnitPrice
     *
     * @mbggenerated
     */
    public Integer getGoodsunitprice() {
        return goodsunitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goodsUnitPrice
     *
     * @param goodsunitprice the value for tb_goods.goodsUnitPrice
     *
     * @mbggenerated
     */
    public void setGoodsunitprice(Integer goodsunitprice) {
        this.goodsunitprice = goodsunitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.goodsImageName
     *
     * @return the value of tb_goods.goodsImageName
     *
     * @mbggenerated
     */
    public String getGoodsimagename() {
        return goodsimagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.goodsImageName
     *
     * @param goodsimagename the value for tb_goods.goodsImageName
     *
     * @mbggenerated
     */
    public void setGoodsimagename(String goodsimagename) {
        this.goodsimagename = goodsimagename == null ? null : goodsimagename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goods.sellCount
     *
     * @return the value of tb_goods.sellCount
     *
     * @mbggenerated
     */
    public Integer getSellcount() {
        return sellcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goods.sellCount
     *
     * @param sellcount the value for tb_goods.sellCount
     *
     * @mbggenerated
     */
    public void setSellcount(Integer sellcount) {
        this.sellcount = sellcount;
    }
}