package com.lut.model;

import java.util.ArrayList;
import java.util.List;

public class TbGoodsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    public TbGoodsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGoodsidIsNull() {
            addCriterion("goodsID is null");
            return (Criteria) this;
        }

        public Criteria andGoodsidIsNotNull() {
            addCriterion("goodsID is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsidEqualTo(Integer value) {
            addCriterion("goodsID =", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidNotEqualTo(Integer value) {
            addCriterion("goodsID <>", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidGreaterThan(Integer value) {
            addCriterion("goodsID >", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidGreaterThanOrEqualTo(Integer value) {
            addCriterion("goodsID >=", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidLessThan(Integer value) {
            addCriterion("goodsID <", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidLessThanOrEqualTo(Integer value) {
            addCriterion("goodsID <=", value, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidIn(List<Integer> values) {
            addCriterion("goodsID in", values, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidNotIn(List<Integer> values) {
            addCriterion("goodsID not in", values, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidBetween(Integer value1, Integer value2) {
            addCriterion("goodsID between", value1, value2, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsidNotBetween(Integer value1, Integer value2) {
            addCriterion("goodsID not between", value1, value2, "goodsid");
            return (Criteria) this;
        }

        public Criteria andGoodsnameIsNull() {
            addCriterion("goodsName is null");
            return (Criteria) this;
        }

        public Criteria andGoodsnameIsNotNull() {
            addCriterion("goodsName is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsnameEqualTo(String value) {
            addCriterion("goodsName =", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameNotEqualTo(String value) {
            addCriterion("goodsName <>", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameGreaterThan(String value) {
            addCriterion("goodsName >", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameGreaterThanOrEqualTo(String value) {
            addCriterion("goodsName >=", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameLessThan(String value) {
            addCriterion("goodsName <", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameLessThanOrEqualTo(String value) {
            addCriterion("goodsName <=", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameLike(String value) {
            addCriterion("goodsName like", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameNotLike(String value) {
            addCriterion("goodsName not like", value, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameIn(List<String> values) {
            addCriterion("goodsName in", values, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameNotIn(List<String> values) {
            addCriterion("goodsName not in", values, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameBetween(String value1, String value2) {
            addCriterion("goodsName between", value1, value2, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodsnameNotBetween(String value1, String value2) {
            addCriterion("goodsName not between", value1, value2, "goodsname");
            return (Criteria) this;
        }

        public Criteria andGoodstypeidIsNull() {
            addCriterion("goodsTypeID is null");
            return (Criteria) this;
        }

        public Criteria andGoodstypeidIsNotNull() {
            addCriterion("goodsTypeID is not null");
            return (Criteria) this;
        }

        public Criteria andGoodstypeidEqualTo(Integer value) {
            addCriterion("goodsTypeID =", value, "goodstypeid");
            return (Criteria) this;
        }

        public Criteria andGoodstypeidNotEqualTo(Integer value) {
            addCriterion("goodsTypeID <>", value, "goodstypeid");
            return (Criteria) this;
        }

        public Criteria andGoodstypeidGreaterThan(Integer value) {
            addCriterion("goodsTypeID >", value, "goodstypeid");
            return (Criteria) this;
        }

        public Criteria andGoodstypeidGreaterThanOrEqualTo(Integer value) {
            addCriterion("goodsTypeID >=", value, "goodstypeid");
            return (Criteria) this;
        }

        public Criteria andGoodstypeidLessThan(Integer value) {
            addCriterion("goodsTypeID <", value, "goodstypeid");
            return (Criteria) this;
        }

        public Criteria andGoodstypeidLessThanOrEqualTo(Integer value) {
            addCriterion("goodsTypeID <=", value, "goodstypeid");
            return (Criteria) this;
        }

        public Criteria andGoodstypeidIn(List<Integer> values) {
            addCriterion("goodsTypeID in", values, "goodstypeid");
            return (Criteria) this;
        }

        public Criteria andGoodstypeidNotIn(List<Integer> values) {
            addCriterion("goodsTypeID not in", values, "goodstypeid");
            return (Criteria) this;
        }

        public Criteria andGoodstypeidBetween(Integer value1, Integer value2) {
            addCriterion("goodsTypeID between", value1, value2, "goodstypeid");
            return (Criteria) this;
        }

        public Criteria andGoodstypeidNotBetween(Integer value1, Integer value2) {
            addCriterion("goodsTypeID not between", value1, value2, "goodstypeid");
            return (Criteria) this;
        }

        public Criteria andGoodsdescriptIsNull() {
            addCriterion("goodsDescript is null");
            return (Criteria) this;
        }

        public Criteria andGoodsdescriptIsNotNull() {
            addCriterion("goodsDescript is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsdescriptEqualTo(String value) {
            addCriterion("goodsDescript =", value, "goodsdescript");
            return (Criteria) this;
        }

        public Criteria andGoodsdescriptNotEqualTo(String value) {
            addCriterion("goodsDescript <>", value, "goodsdescript");
            return (Criteria) this;
        }

        public Criteria andGoodsdescriptGreaterThan(String value) {
            addCriterion("goodsDescript >", value, "goodsdescript");
            return (Criteria) this;
        }

        public Criteria andGoodsdescriptGreaterThanOrEqualTo(String value) {
            addCriterion("goodsDescript >=", value, "goodsdescript");
            return (Criteria) this;
        }

        public Criteria andGoodsdescriptLessThan(String value) {
            addCriterion("goodsDescript <", value, "goodsdescript");
            return (Criteria) this;
        }

        public Criteria andGoodsdescriptLessThanOrEqualTo(String value) {
            addCriterion("goodsDescript <=", value, "goodsdescript");
            return (Criteria) this;
        }

        public Criteria andGoodsdescriptLike(String value) {
            addCriterion("goodsDescript like", value, "goodsdescript");
            return (Criteria) this;
        }

        public Criteria andGoodsdescriptNotLike(String value) {
            addCriterion("goodsDescript not like", value, "goodsdescript");
            return (Criteria) this;
        }

        public Criteria andGoodsdescriptIn(List<String> values) {
            addCriterion("goodsDescript in", values, "goodsdescript");
            return (Criteria) this;
        }

        public Criteria andGoodsdescriptNotIn(List<String> values) {
            addCriterion("goodsDescript not in", values, "goodsdescript");
            return (Criteria) this;
        }

        public Criteria andGoodsdescriptBetween(String value1, String value2) {
            addCriterion("goodsDescript between", value1, value2, "goodsdescript");
            return (Criteria) this;
        }

        public Criteria andGoodsdescriptNotBetween(String value1, String value2) {
            addCriterion("goodsDescript not between", value1, value2, "goodsdescript");
            return (Criteria) this;
        }

        public Criteria andGoodsunitpriceIsNull() {
            addCriterion("goodsUnitPrice is null");
            return (Criteria) this;
        }

        public Criteria andGoodsunitpriceIsNotNull() {
            addCriterion("goodsUnitPrice is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsunitpriceEqualTo(Integer value) {
            addCriterion("goodsUnitPrice =", value, "goodsunitprice");
            return (Criteria) this;
        }

        public Criteria andGoodsunitpriceNotEqualTo(Integer value) {
            addCriterion("goodsUnitPrice <>", value, "goodsunitprice");
            return (Criteria) this;
        }

        public Criteria andGoodsunitpriceGreaterThan(Integer value) {
            addCriterion("goodsUnitPrice >", value, "goodsunitprice");
            return (Criteria) this;
        }

        public Criteria andGoodsunitpriceGreaterThanOrEqualTo(Integer value) {
            addCriterion("goodsUnitPrice >=", value, "goodsunitprice");
            return (Criteria) this;
        }

        public Criteria andGoodsunitpriceLessThan(Integer value) {
            addCriterion("goodsUnitPrice <", value, "goodsunitprice");
            return (Criteria) this;
        }

        public Criteria andGoodsunitpriceLessThanOrEqualTo(Integer value) {
            addCriterion("goodsUnitPrice <=", value, "goodsunitprice");
            return (Criteria) this;
        }

        public Criteria andGoodsunitpriceIn(List<Integer> values) {
            addCriterion("goodsUnitPrice in", values, "goodsunitprice");
            return (Criteria) this;
        }

        public Criteria andGoodsunitpriceNotIn(List<Integer> values) {
            addCriterion("goodsUnitPrice not in", values, "goodsunitprice");
            return (Criteria) this;
        }

        public Criteria andGoodsunitpriceBetween(Integer value1, Integer value2) {
            addCriterion("goodsUnitPrice between", value1, value2, "goodsunitprice");
            return (Criteria) this;
        }

        public Criteria andGoodsunitpriceNotBetween(Integer value1, Integer value2) {
            addCriterion("goodsUnitPrice not between", value1, value2, "goodsunitprice");
            return (Criteria) this;
        }

        public Criteria andGoodsimagenameIsNull() {
            addCriterion("goodsImageName is null");
            return (Criteria) this;
        }

        public Criteria andGoodsimagenameIsNotNull() {
            addCriterion("goodsImageName is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsimagenameEqualTo(String value) {
            addCriterion("goodsImageName =", value, "goodsimagename");
            return (Criteria) this;
        }

        public Criteria andGoodsimagenameNotEqualTo(String value) {
            addCriterion("goodsImageName <>", value, "goodsimagename");
            return (Criteria) this;
        }

        public Criteria andGoodsimagenameGreaterThan(String value) {
            addCriterion("goodsImageName >", value, "goodsimagename");
            return (Criteria) this;
        }

        public Criteria andGoodsimagenameGreaterThanOrEqualTo(String value) {
            addCriterion("goodsImageName >=", value, "goodsimagename");
            return (Criteria) this;
        }

        public Criteria andGoodsimagenameLessThan(String value) {
            addCriterion("goodsImageName <", value, "goodsimagename");
            return (Criteria) this;
        }

        public Criteria andGoodsimagenameLessThanOrEqualTo(String value) {
            addCriterion("goodsImageName <=", value, "goodsimagename");
            return (Criteria) this;
        }

        public Criteria andGoodsimagenameLike(String value) {
            addCriterion("goodsImageName like", value, "goodsimagename");
            return (Criteria) this;
        }

        public Criteria andGoodsimagenameNotLike(String value) {
            addCriterion("goodsImageName not like", value, "goodsimagename");
            return (Criteria) this;
        }

        public Criteria andGoodsimagenameIn(List<String> values) {
            addCriterion("goodsImageName in", values, "goodsimagename");
            return (Criteria) this;
        }

        public Criteria andGoodsimagenameNotIn(List<String> values) {
            addCriterion("goodsImageName not in", values, "goodsimagename");
            return (Criteria) this;
        }

        public Criteria andGoodsimagenameBetween(String value1, String value2) {
            addCriterion("goodsImageName between", value1, value2, "goodsimagename");
            return (Criteria) this;
        }

        public Criteria andGoodsimagenameNotBetween(String value1, String value2) {
            addCriterion("goodsImageName not between", value1, value2, "goodsimagename");
            return (Criteria) this;
        }

        public Criteria andSellcountIsNull() {
            addCriterion("sellCount is null");
            return (Criteria) this;
        }

        public Criteria andSellcountIsNotNull() {
            addCriterion("sellCount is not null");
            return (Criteria) this;
        }

        public Criteria andSellcountEqualTo(Integer value) {
            addCriterion("sellCount =", value, "sellcount");
            return (Criteria) this;
        }

        public Criteria andSellcountNotEqualTo(Integer value) {
            addCriterion("sellCount <>", value, "sellcount");
            return (Criteria) this;
        }

        public Criteria andSellcountGreaterThan(Integer value) {
            addCriterion("sellCount >", value, "sellcount");
            return (Criteria) this;
        }

        public Criteria andSellcountGreaterThanOrEqualTo(Integer value) {
            addCriterion("sellCount >=", value, "sellcount");
            return (Criteria) this;
        }

        public Criteria andSellcountLessThan(Integer value) {
            addCriterion("sellCount <", value, "sellcount");
            return (Criteria) this;
        }

        public Criteria andSellcountLessThanOrEqualTo(Integer value) {
            addCriterion("sellCount <=", value, "sellcount");
            return (Criteria) this;
        }

        public Criteria andSellcountIn(List<Integer> values) {
            addCriterion("sellCount in", values, "sellcount");
            return (Criteria) this;
        }

        public Criteria andSellcountNotIn(List<Integer> values) {
            addCriterion("sellCount not in", values, "sellcount");
            return (Criteria) this;
        }

        public Criteria andSellcountBetween(Integer value1, Integer value2) {
            addCriterion("sellCount between", value1, value2, "sellcount");
            return (Criteria) this;
        }

        public Criteria andSellcountNotBetween(Integer value1, Integer value2) {
            addCriterion("sellCount not between", value1, value2, "sellcount");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_goods
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}