package com.lut.model;

public class TbGoodstype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goodstype.goodsTypeID
     *
     * @mbggenerated
     */
    private Integer goodstypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_goodstype.goodsTypeName
     *
     * @mbggenerated
     */
    private String goodstypename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goodstype.goodsTypeID
     *
     * @return the value of tb_goodstype.goodsTypeID
     *
     * @mbggenerated
     */
    public Integer getGoodstypeid() {
        return goodstypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goodstype.goodsTypeID
     *
     * @param goodstypeid the value for tb_goodstype.goodsTypeID
     *
     * @mbggenerated
     */
    public void setGoodstypeid(Integer goodstypeid) {
        this.goodstypeid = goodstypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_goodstype.goodsTypeName
     *
     * @return the value of tb_goodstype.goodsTypeName
     *
     * @mbggenerated
     */
    public String getGoodstypename() {
        return goodstypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_goodstype.goodsTypeName
     *
     * @param goodstypename the value for tb_goodstype.goodsTypeName
     *
     * @mbggenerated
     */
    public void setGoodstypename(String goodstypename) {
        this.goodstypename = goodstypename == null ? null : goodstypename.trim();
    }
}