package com.lut.model;

public class TbManager {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.managerName
     *
     * @mbggenerated
     */
    private String managername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_manager.managerPwd
     *
     * @mbggenerated
     */
    private String managerpwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager.managerName
     *
     * @return the value of tb_manager.managerName
     *
     * @mbggenerated
     */
    public String getManagername() {
        return managername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager.managerName
     *
     * @param managername the value for tb_manager.managerName
     *
     * @mbggenerated
     */
    public void setManagername(String managername) {
        this.managername = managername == null ? null : managername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_manager.managerPwd
     *
     * @return the value of tb_manager.managerPwd
     *
     * @mbggenerated
     */
    public String getManagerpwd() {
        return managerpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_manager.managerPwd
     *
     * @param managerpwd the value for tb_manager.managerPwd
     *
     * @mbggenerated
     */
    public void setManagerpwd(String managerpwd) {
        this.managerpwd = managerpwd == null ? null : managerpwd.trim();
    }
}