package com.lut.model;

public class TbOrderdetailKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderdetail.orderID
     *
     * @mbggenerated
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_orderdetail.goodsID
     *
     * @mbggenerated
     */
    private Integer goodsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderdetail.orderID
     *
     * @return the value of tb_orderdetail.orderID
     *
     * @mbggenerated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderdetail.orderID
     *
     * @param orderid the value for tb_orderdetail.orderID
     *
     * @mbggenerated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_orderdetail.goodsID
     *
     * @return the value of tb_orderdetail.goodsID
     *
     * @mbggenerated
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_orderdetail.goodsID
     *
     * @param goodsid the value for tb_orderdetail.goodsID
     *
     * @mbggenerated
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }
}