package com.lut.model;

import java.util.Date;

public class TbOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.orderID
     *
     * @mbggenerated
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.customerName
     *
     * @mbggenerated
     */
    private String customername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.totalMoney
     *
     * @mbggenerated
     */
    private Integer totalmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.orderDate
     *
     * @mbggenerated
     */
    private Date orderdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.orderState
     *
     * @mbggenerated
     */
    private String orderstate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.orderID
     *
     * @return the value of tb_order.orderID
     *
     * @mbggenerated
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.orderID
     *
     * @param orderid the value for tb_order.orderID
     *
     * @mbggenerated
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.customerName
     *
     * @return the value of tb_order.customerName
     *
     * @mbggenerated
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.customerName
     *
     * @param customername the value for tb_order.customerName
     *
     * @mbggenerated
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.totalMoney
     *
     * @return the value of tb_order.totalMoney
     *
     * @mbggenerated
     */
    public Integer getTotalmoney() {
        return totalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.totalMoney
     *
     * @param totalmoney the value for tb_order.totalMoney
     *
     * @mbggenerated
     */
    public void setTotalmoney(Integer totalmoney) {
        this.totalmoney = totalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.orderDate
     *
     * @return the value of tb_order.orderDate
     *
     * @mbggenerated
     */
    public Date getOrderdate() {
        return orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.orderDate
     *
     * @param orderdate the value for tb_order.orderDate
     *
     * @mbggenerated
     */
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.orderState
     *
     * @return the value of tb_order.orderState
     *
     * @mbggenerated
     */
    public String getOrderstate() {
        return orderstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.orderState
     *
     * @param orderstate the value for tb_order.orderState
     *
     * @mbggenerated
     */
    public void setOrderstate(String orderstate) {
        this.orderstate = orderstate == null ? null : orderstate.trim();
    }
}