package com.lut.model;

public class TbReceive {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receive.receiveID
     *
     * @mbggenerated
     */
    private Integer receiveid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receive.receiveName
     *
     * @mbggenerated
     */
    private String receivename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receive.receiveAddress
     *
     * @mbggenerated
     */
    private String receiveaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receive.receiveTel
     *
     * @mbggenerated
     */
    private Integer receivetel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_receive.customerName
     *
     * @mbggenerated
     */
    private String customername;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receive.receiveID
     *
     * @return the value of tb_receive.receiveID
     *
     * @mbggenerated
     */
    public Integer getReceiveid() {
        return receiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receive.receiveID
     *
     * @param receiveid the value for tb_receive.receiveID
     *
     * @mbggenerated
     */
    public void setReceiveid(Integer receiveid) {
        this.receiveid = receiveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receive.receiveName
     *
     * @return the value of tb_receive.receiveName
     *
     * @mbggenerated
     */
    public String getReceivename() {
        return receivename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receive.receiveName
     *
     * @param receivename the value for tb_receive.receiveName
     *
     * @mbggenerated
     */
    public void setReceivename(String receivename) {
        this.receivename = receivename == null ? null : receivename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receive.receiveAddress
     *
     * @return the value of tb_receive.receiveAddress
     *
     * @mbggenerated
     */
    public String getReceiveaddress() {
        return receiveaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receive.receiveAddress
     *
     * @param receiveaddress the value for tb_receive.receiveAddress
     *
     * @mbggenerated
     */
    public void setReceiveaddress(String receiveaddress) {
        this.receiveaddress = receiveaddress == null ? null : receiveaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receive.receiveTel
     *
     * @return the value of tb_receive.receiveTel
     *
     * @mbggenerated
     */
    public Integer getReceivetel() {
        return receivetel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receive.receiveTel
     *
     * @param receivetel the value for tb_receive.receiveTel
     *
     * @mbggenerated
     */
    public void setReceivetel(Integer receivetel) {
        this.receivetel = receivetel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_receive.customerName
     *
     * @return the value of tb_receive.customerName
     *
     * @mbggenerated
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_receive.customerName
     *
     * @param customername the value for tb_receive.customerName
     *
     * @mbggenerated
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }
}