package com.lut.dao;

import com.lut.model.TbCustomer;
import com.lut.model.TbCustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated
     */
    int countByExample(TbCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated
     */
    int deleteByExample(TbCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String customername);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated
     */
    int insert(TbCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated
     */
    int insertSelective(TbCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated
     */
    List<TbCustomer> selectByExample(TbCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated
     */
    TbCustomer selectByPrimaryKey(String customername);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbCustomer record, @Param("example") TbCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbCustomer record, @Param("example") TbCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbCustomer record);
}