package com.lut.dao;

import com.lut.model.TbCustomer;
import com.lut.model.TbCustomerExample;

import java.util.LinkedList;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Component;


@Component
public interface TbCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated
     */
    int countByExample(TbCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated
     */
    int deleteByExample(TbCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String customername);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated
     */
    int insert(TbCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated
     */
    int insertSelective(TbCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated
     */
    List<TbCustomer> selectByExample(TbCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated
     */
    TbCustomer selectByPrimaryKey(String customername);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbCustomer record, @Param("example") TbCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbCustomer record, @Param("example") TbCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_customer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbCustomer record);

    @Select("select customerName   from tb_customer where customerName =#{username} and customerPass =#{password}")
//    select customerName   from tb_customer where customerName =#{username} and customerPass =#{password}
    String login(@Param("username") String username,@Param("password") String password);


    /**
     * 以下为测试天坑的sql
     * @return
     */
////    @Select("select customername from tb_customer")
//      @Select("select customerName  from tb_customer")
////    select customerName  from tb_customer
//    String test();
}