package com.lut.dao;

import com.lut.model.TbGoodstype;
import com.lut.model.TbGoodstypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbGoodstypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goodstype
     *
     * @mbggenerated
     */
    int countByExample(TbGoodstypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goodstype
     *
     * @mbggenerated
     */
    int deleteByExample(TbGoodstypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goodstype
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer goodstypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goodstype
     *
     * @mbggenerated
     */
    int insert(TbGoodstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goodstype
     *
     * @mbggenerated
     */
    int insertSelective(TbGoodstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goodstype
     *
     * @mbggenerated
     */
    List<TbGoodstype> selectByExample(TbGoodstypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goodstype
     *
     * @mbggenerated
     */
    TbGoodstype selectByPrimaryKey(Integer goodstypeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goodstype
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbGoodstype record, @Param("example") TbGoodstypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goodstype
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbGoodstype record, @Param("example") TbGoodstypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goodstype
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbGoodstype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goodstype
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbGoodstype record);
}