package com.lut.dao;

import com.lut.model.TbGoods;
import com.lut.model.TbGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface TbGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    int countByExample(TbGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    int deleteByExample(TbGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer goodsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    int insert(TbGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    int insertSelective(TbGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    List<TbGoods> selectByExample(TbGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    @Select("select * from tb_goods")
    List<TbGoods> findAllGoods();
    //目前模糊查询时以正则匹配输入的字符，返回结果
    @Select("select * from tb_goods where goodsName like [${goodsName}]")
    List<TbGoods> findGoodsByFiled(@Param("goodsName") String goodsName);


    TbGoods selectByPrimaryKey(Integer goodsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbGoods record, @Param("example") TbGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbGoods record, @Param("example") TbGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbGoods record);

    @Select("select goodsUnitPrice from tb_goods where goodsID = #{id}")
    int getGoodsPriceByGoodsId(@Param("id") Integer goodsId);
}