package com.lut.dao;

import com.lut.model.TbManager;
import com.lut.model.TbManagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbggenerated
     */
    int countByExample(TbManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbggenerated
     */
    int deleteByExample(TbManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String managername);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbggenerated
     */
    int insert(TbManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbggenerated
     */
    int insertSelective(TbManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbggenerated
     */
    List<TbManager> selectByExample(TbManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbggenerated
     */
    TbManager selectByPrimaryKey(String managername);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbManager record, @Param("example") TbManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbManager record, @Param("example") TbManagerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbManager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_manager
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbManager record);
}