package com.lut.dao;

import com.lut.model.TbOrderdetailExample;
import com.lut.model.TbOrderdetailKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbOrderdetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderdetail
     *
     * @mbggenerated
     */
    int countByExample(TbOrderdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderdetail
     *
     * @mbggenerated
     */
    int deleteByExample(TbOrderdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderdetail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(TbOrderdetailKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderdetail
     *
     * @mbggenerated
     */
    int insert(TbOrderdetailKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderdetail
     *
     * @mbggenerated
     */
    int insertSelective(TbOrderdetailKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderdetail
     *
     * @mbggenerated
     */
    List<TbOrderdetailKey> selectByExample(TbOrderdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderdetail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbOrderdetailKey record, @Param("example") TbOrderdetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_orderdetail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbOrderdetailKey record, @Param("example") TbOrderdetailExample example);
}