package com.lut.dao;

import com.lut.model.TbReceive;
import com.lut.model.TbReceiveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface TbReceiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_receive
     *
     * @mbggenerated
     */
    int countByExample(TbReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_receive
     *
     * @mbggenerated
     */
    int deleteByExample(TbReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_receive
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer receiveid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_receive
     *
     * @mbggenerated
     */
    int insert(TbReceive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_receive
     *
     * @mbggenerated
     */
    int insertSelective(TbReceive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_receive
     *
     * @mbggenerated
     */
    List<TbReceive> selectByExample(TbReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_receive
     *
     * @mbggenerated
     */
    TbReceive selectByPrimaryKey(Integer receiveid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_receive
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TbReceive record, @Param("example") TbReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_receive
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TbReceive record, @Param("example") TbReceiveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_receive
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbReceive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_receive
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TbReceive record);

    //查询所有收货地址
    @Select("select * from tb_receive where customerName = #{username}")
    List<TbReceive> showAll(@Param("username") String username);
}